[workspace]
members = ["confidence"]

[package]
name = "cbdr"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
confidence = { path = "confidence" }
csv = "1.1"
env_logger = "0.7"
log = "0.4"
rand = "0.7"
rolling-stats = "0.3"
serde_json = "1.0"
structopt = "0.3"
tabwriter = "1.1"
