[package]
name = "cbdr"
description = "Tools for comparitive benchmarking"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
confidence = { path = "confidence" }
csv = "1.1"
env_logger = "0.7"
log = "0.4"
rand = "0.7"
rolling-stats = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tabwriter = "1.1"
term = "0.6"

[profile.release]
debug = true

[workspace]
members = ["confidence"]
