[package]
name = "cbdr"
description = "Tools for comparitive benchmarking"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
arc-swap = "0.4"
confidence = { path = "confidence" }
csv = "1.1"
env_logger = "0.7"
log = "0.4"
once_cell = "1.2"
rand = "0.7"
rolling-stats = "0.3"
serde_json = "1.0"
structopt = "0.3"
tabwriter = { version = "1.1", features = ["ansi_formatting"] }
term = "0.6"
time_cmd = { path = "time_cmd" }

[profile.release]
debug = true

[workspace]
members = ["confidence", "time_cmd"]
