[package]
name = "behrens-fisher"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
statrs = { git = "https://github.com/asayers/statrs.git", branch = "student_invcdf" }
