[package]
name = "time_cmd"
description = "Time how long a process takes to run"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"
repository = "https://github.com/asayers/cbdr"

[dependencies]
libc = "0.2"
